# Generated by Django 4.2.15 on 2024-08-16 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postcomment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, default='123456789', help_text='Telefon raqamini 9 ta raqam shaklida kiriting.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Telefon raqami 9 ta raqamdan iborat bo'lishi kerak.", regex='^\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='author',
            name='worker',
            field=models.CharField(blank=True, default='', help_text='Sohangizni kiriting.', max_length=150),
        ),
    ]
