# Generated by Django 4.2.15 on 2024-08-16 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_author_address_author_phone_number_author_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Telefon raqamini 9 ta raqam shaklida kiriting.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Telefon raqami 9 ta raqamdan iborat bo'lishi kerak.", regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pic.jpg', upload_to='profile_images'),
        ),
    ]
