# Generated by Django 4.2.15 on 2024-08-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_author_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text="Postning to'liq ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text="Kerakli bo'limni tanlang", on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Postga oid rasm', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Postning qisqacha mazmuni', max_length=200),
        ),
    ]
