# Generated by Django 4.2.15 on 2024-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_body_alter_post_category_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/profile_pic.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default.jpg', help_text='Postga oid rasm', upload_to='post_images'),
        ),
    ]
