# Generated by Django 4.2.15 on 2024-08-19 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_author_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ismingizni kiriting.', max_length=150)),
                ('phone_number', models.CharField(help_text='Telefon raqamini 9 ta raqam shaklida kiriting.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Telefon raqami 9 ta raqamdan iborat bo'lishi kerak.", regex='^\\d{9}$')])),
                ('message', models.TextField()),
            ],
        ),
    ]
