# Generated by Django 4.2.15 on 2024-08-20 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_message',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
